# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-15 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20190415_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
